@host = http://localhost:3000

### Register a new user
POST {{host}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "teacher2@test.com",
  "password": "TeacherPass123",
  "name": "Demo Teacher 2"
}

### Login and capture JWT token
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "teacher@test.com",
  "password": "TeacherPass123"
}

> {%
    client.global.set("api_token", response.body["token"]);
%}

### Login and capture JWT token
POST {{host}}/auth/login/student
Content-Type: application/json

{
  "code": "148779",
  "username": "mokakit",
  "password": "wa673478"
}

### Get User Response
GET {{host}}/api/me
Content-Type: application/json
Authorization: Bearer {{api_token}}