### @name = Dev
@host = http://localhost:3000

### Get all users (protected)
GET {{host}}/api/users
Authorization: Bearer {{api_token}}

> {%
    client.global.set("user_id", response.body[0]["id"]);
%}

### Get a single user by ID (protected)
GET {{host}}/api/users/{{user_id}}
Authorization: Bearer {{api_token}}

### Update a user (protected)
PUT {{host}}/api/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{api_token}}

{
  "name": "Alice Updated",
  "password": "NewPass456"
}

### Delete a user (protected)
DELETE {{host}}/api/users/{{user_id}}
Authorization: Bearer {{api_token}}

### Restore a user (protected)
PATCH {{host}}/api/users/{{user_id}}/restore
Authorization: Bearer {{api_token}}